export const countryCapitals = {
  Afghanistan: "Kabul",
  Australia: "Canberra",
  Brazil: "Brasília",
  Canada: "Ottawa",
  China: "Beijing",
  Egypt: "Cairo",
  France: "Paris",
  Germany: "Berlin",
  India: "New Delhi",
  Italy: "Rome",
  Japan: "Tokyo",
  Mexico: "Mexico City",
  Netherlands: "Amsterdam",
  Nigeria: "Abuja",
  Russia: "Moscow",
  SaudiArabia: "Riyadh",
  SouthAfrica: "Pretoria",
  SouthKorea: "Seoul",
  UnitedKingdom: "London",
  UnitedStates: "Washington, D.C.",
};
